### ISSUE TITLE
Create specific mock data for each community in the subcommunity pages

### ISSUE THREAD

**Issue by jenniferyuuu** [agiledev-students-fall2024/4-final-project-seraphim#83]
Related to User Story #6

_By definition, this `task` represents one unit of work that is part of the implementation of a single user story._

**Comment by saharbueno** [comment]
Related to User Story #1, User Story #2,  User Story #3  User Story #4,  User Story #5,  User Story #6,  User Story #7,  User Story #8,  User Story #9,  User Story #10,  User Story #11,  User Story #12,  User Story #13,  User Story #14,  User Story #15
